version: '3'
services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config
      - ./.docker/mercure/Caddyfile.dev:/etc/caddy/Caddyfile.dev
    ports:
      - "8090:80"

  php:
    build: .docker/php
    volumes:
      - ./app:/app
      - ./.docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    depends_on:
      - mysql

  nginx:
    image: nginx
    depends_on:
      - php
      - mercure
    volumes:
      - ./app:/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - api_php_socket:/var/run/php
    ports:
      - '8080:80'

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}
      - PMA_HOST=mysql
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - '8081:80'

volumes:
    api_php_socket: {}
    mercure_data: { }
    mercure_config: { }
