api_platform:
    title: 'Blog API'
    version: 0.9
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
    patch_formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
    mercure: ~