api_platform:
    title: 'Blog API'
    version: 0.9
    enable_swagger_ui: false
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
    patch_formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
#    swagger:
#        api_keys:
#            JWT:
#                name: Authorization
#                type: header